version: '2'
services:
  jenkinsmaster:
    build: jenkins-master
    volumes:
      - jenkinsdata:/var/jenkins_home
      - jenkinslogs:/var/log/jenkins
    ports:
      - "50000:50000"
      - "8080:8080"
    privileged: true
  jenkinsnginx:
    build: jenkins-nginx
    ports:
      - "80:80"
    links:
      - jenkinsmaster:jenkins-master

volumes:
  jenkinsdata: #declare volume
  jenkinslogs: #declare volume