jenkinsdata:
  build: jenkins-data
jenkinsmaster:
  build: jenkins-master
  volumes_from:
    - jenkinsdata
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
  ports:
    - "50000:50000"
    - "8080:8080"
  restart: always
jenkinsnginx:
  build: jenkins-nginx
  ports:
    - "80:80"
  links:
    - jenkinsmaster:jenkins-master
  restart: always
